package dependabot

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"strings"

	"gopkg.in/yaml.v3"
)

// Discovery is the result of generating or extending a Dependabot config from
// the ecosystems detected in a repository.
type Discovery struct {
	Owner string
	Repo  string
	Path  string

	Data    []byte   // the resulting file contents
	Created bool     // the file did not exist and was scaffolded in full
	Changed bool     // Data differs from the existing file (it was written)
	Added   []string // ecosystems added (sorted as detected)
	Notes   []string // human-readable notes (e.g. "already covered")
}

// Discover builds a best-practice Dependabot config from the detected
// ecosystems. With no existing file it scaffolds a complete config; with one it
// appends an update entry for every detected ecosystem the config does not yet
// cover, preserving the existing comments and key order.
func Discover(existing []byte, detected []Detected) (Discovery, error) {
	if strings.TrimSpace(string(existing)) == "" {
		return create(detected)
	}
	return extend(existing, detected)
}

// create scaffolds a full config from scratch.
func create(detected []Detected) (Discovery, error) {
	if len(detected) == 0 {
		return Discovery{Notes: []string{"no ecosystems detected — nothing to scaffold"}}, nil
	}
	cfg := Config{Version: new(2)}
	var added []string
	for _, d := range detected {
		cfg.Updates = append(cfg.Updates, bestPracticeUpdate(d.Ecosystem, d.Directories))
		added = append(added, d.Ecosystem)
	}
	data, err := marshalConfig(cfg)
	if err != nil {
		return Discovery{}, err
	}
	return Discovery{Data: data, Created: true, Changed: true, Added: added}, nil
}

// extend appends entries for uncovered ecosystems to an existing config.
func extend(existing []byte, detected []Detected) (Discovery, error) {
	cfg, err := Parse(existing)
	if err != nil {
		return Discovery{}, err
	}
	covered, _, _ := configIndex(cfg)

	var newUpdates []Update
	var added []string
	for _, d := range detected {
		if covered[d.Ecosystem] {
			continue
		}
		newUpdates = append(newUpdates, bestPracticeUpdate(d.Ecosystem, d.Directories))
		added = append(added, d.Ecosystem)
	}
	if len(newUpdates) == 0 {
		return Discovery{Data: existing, Notes: []string{"every detected ecosystem is already covered"}}, nil
	}
	data, err := appendUpdates(existing, newUpdates)
	if err != nil {
		return Discovery{}, err
	}
	return Discovery{Data: data, Changed: true, Added: added}, nil
}

// bestPracticeUpdate builds a recommended update entry for one ecosystem: a
// weekly schedule, an open-PR limit, a grouping of minor/patch bumps, a label,
// and a commit-message prefix. Assignees are intentionally left out — shuck
// cannot know who should own the PRs — and noted for the caller to fill in.
func bestPracticeUpdate(eco string, dirs []string) Update {
	u := Update{PackageEcosystem: eco}
	switch {
	case len(dirs) <= 1:
		dir := "/"
		if len(dirs) == 1 {
			dir = dirs[0]
		}
		u.Directory = dir
	default:
		u.Directories = dirs
	}
	u.Schedule = &Schedule{Interval: "weekly"}
	u.OpenPullRequestsLimit = new(10)
	u.Labels = []string{"dependencies"}
	u.Groups = map[string]Group{
		eco + "-minor-and-patch": {
			Patterns:    []string{"*"},
			UpdateTypes: []string{"minor", "patch"},
		},
	}
	u.CommitMessage = &CommitMessage{Prefix: commitPrefix(eco)}
	return u
}

// commitPrefix picks a conventional-commit prefix for an ecosystem's update PRs.
func commitPrefix(eco string) string {
	if eco == "github-actions" {
		return "ci"
	}
	return "chore"
}

// marshalConfig renders a freshly-built config with a short header comment.
func marshalConfig(cfg Config) ([]byte, error) {
	body, err := marshalYAML(cfg)
	if err != nil {
		return nil, err
	}
	const header = "# Dependabot configuration — https://docs.github.com/code-security/dependabot\n" +
		"# Generated by `shuck dependabot discover`. Review and add assignees.\n"
	return append([]byte(header), body...), nil
}

// appendUpdates adds the new update entries to the `updates` sequence of an
// existing document, preserving its comments and key order via yaml.Node.
func appendUpdates(existing []byte, newUpdates []Update) ([]byte, error) {
	var doc yaml.Node
	if err := yaml.Unmarshal(existing, &doc); err != nil {
		return nil, fmt.Errorf("parse existing config: %w", err)
	}
	if len(doc.Content) == 0 || doc.Content[0].Kind != yaml.MappingNode {
		return nil, fmt.Errorf("existing config is not a mapping")
	}
	root := doc.Content[0]
	seq := mappingValue(root, "updates")
	if seq == nil {
		seq = &yaml.Node{Kind: yaml.SequenceNode}
		root.Content = append(root.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: "updates"}, seq)
	}
	if seq.Kind != yaml.SequenceNode {
		return nil, fmt.Errorf("'updates' in the existing config is not a list")
	}
	for _, u := range newUpdates {
		var n yaml.Node
		if err := n.Encode(u); err != nil {
			return nil, fmt.Errorf("encode update entry: %w", err)
		}
		seq.Content = append(seq.Content, &n)
	}
	return marshalNode(&doc)
}

// mappingValue returns the value node for key in a mapping node, or nil.
func mappingValue(m *yaml.Node, key string) *yaml.Node {
	for i := 0; i+1 < len(m.Content); i += 2 {
		if m.Content[i].Value == key {
			return m.Content[i+1]
		}
	}
	return nil
}

func marshalYAML(v any) ([]byte, error) {
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(v); err != nil {
		_ = enc.Close()
		return nil, fmt.Errorf("marshal dependabot config: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func marshalNode(doc *yaml.Node) ([]byte, error) {
	return marshalYAML(doc)
}

// RenderDiscovery writes the human-readable summary of a discover run to w.
// dryRun switches the verbs to the conditional and prints the would-be file.
func RenderDiscovery(w io.Writer, d *Discovery, dryRun bool) {
	fmt.Fprintf(w, "%s/%s — dependabot discover\n", d.Owner, d.Repo)
	if d.Path != "" {
		fmt.Fprintf(w, "config: %s\n", d.Path)
	}

	switch {
	case d.Created:
		verb := "Created"
		if dryRun {
			verb = "Would create"
		}
		fmt.Fprintf(w, "\n%s %s with %d update entry(ies): %s\n", verb, d.Path, len(d.Added), strings.Join(d.Added, ", "))
	case len(d.Added) > 0:
		verb := "Added"
		if dryRun {
			verb = "Would add"
		}
		fmt.Fprintf(w, "\n%s %d ecosystem(s) to %s: %s\n", verb, len(d.Added), d.Path, strings.Join(d.Added, ", "))
	default:
		fmt.Fprintf(w, "\n✓ %s already covers every detected ecosystem — nothing to do.\n", d.Path)
	}

	for _, n := range d.Notes {
		fmt.Fprintf(w, "  – %s\n", n)
	}

	if d.Changed && len(d.Added) > 0 {
		fmt.Fprintf(w, "\n%s", d.Data)
	}
}

// DiscoveryDocument is the stable, machine-readable shape of
// `shuck dependabot discover --json`.
type DiscoveryDocument struct {
	SchemaVersion int      `json:"schema_version"`
	Repo          Repo     `json:"repo"`
	Path          string   `json:"path"`
	Created       bool     `json:"created"`
	Updated       bool     `json:"updated"`
	UpToDate      bool     `json:"up_to_date"`
	Added         []string `json:"added"`
	Notes         []string `json:"notes"`
	Config        string   `json:"config"`
}

// NewDiscoveryDocument projects a discovery into the stable JSON document. The
// slices are always non-nil so they serialize as [] rather than null.
func NewDiscoveryDocument(d *Discovery) DiscoveryDocument {
	added := d.Added
	if added == nil {
		added = []string{}
	}
	notes := d.Notes
	if notes == nil {
		notes = []string{}
	}
	return DiscoveryDocument{
		SchemaVersion: SchemaVersion,
		Repo:          Repo{Owner: d.Owner, Repo: d.Repo},
		Path:          d.Path,
		Created:       d.Created,
		Updated:       !d.Created && len(d.Added) > 0,
		UpToDate:      !d.Changed,
		Added:         added,
		Notes:         notes,
		Config:        string(d.Data),
	}
}

// EncodeDiscoveryJSON writes the discovery as an indented JSON document with a
// trailing newline.
func EncodeDiscoveryJSON(w io.Writer, d *Discovery) error {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(NewDiscoveryDocument(d))
}
