package dependabot

import (
	"bytes"
	"encoding/json"
	"strings"
	"testing"
)

func TestDiscoverCreate(t *testing.T) {
	detected := []Detected{
		{Ecosystem: "gomod", Directories: []string{"/"}},
		{Ecosystem: "npm", Directories: []string{"/a", "/b"}},
	}
	d, err := Discover(nil, detected)
	if err != nil {
		t.Fatalf("Discover: %v", err)
	}
	if !d.Created || !d.Changed {
		t.Fatalf("expected created+changed, got %+v", d)
	}
	if len(d.Added) != 2 {
		t.Errorf("added = %v", d.Added)
	}
	// The generated config must round-trip through the strict parser.
	cfg, err := Parse(d.Data)
	if err != nil {
		t.Fatalf("generated config does not parse: %v\n%s", err, d.Data)
	}
	if len(cfg.Updates) != 2 {
		t.Fatalf("updates = %d", len(cfg.Updates))
	}
	// Single-dir uses `directory`, multi-dir uses `directories`.
	body := string(d.Data)
	if !strings.Contains(body, "package-ecosystem: gomod") || !strings.Contains(body, "directories:") {
		t.Errorf("unexpected body:\n%s", body)
	}
	if !strings.Contains(body, "Generated by `shuck dependabot discover`") {
		t.Error("missing header comment")
	}
	// Best-practice fields are present.
	for _, want := range []string{"interval: weekly", "open-pull-requests-limit: 10", "labels:", "groups:", "prefix:"} {
		if !strings.Contains(body, want) {
			t.Errorf("generated config missing %q:\n%s", want, body)
		}
	}
}

func TestDiscoverCreateNoEcosystems(t *testing.T) {
	d, err := Discover(nil, nil)
	if err != nil {
		t.Fatalf("Discover: %v", err)
	}
	if d.Changed || d.Created {
		t.Errorf("nothing to scaffold: %+v", d)
	}
	if len(d.Notes) == 0 {
		t.Error("expected a note")
	}
}

func TestDiscoverExtend(t *testing.T) {
	existing := []byte(`version: 2
updates:
  # keep me
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
`)
	detected := []Detected{
		{Ecosystem: "gomod", Directories: []string{"/"}},
		{Ecosystem: "docker", Directories: []string{"/"}},
	}
	d, err := Discover(existing, detected)
	if err != nil {
		t.Fatalf("Discover: %v", err)
	}
	if d.Created {
		t.Error("should not be created")
	}
	if !d.Changed || len(d.Added) != 1 || d.Added[0] != "docker" {
		t.Fatalf("expected docker added, got %+v", d)
	}
	body := string(d.Data)
	if !strings.Contains(body, "# keep me") {
		t.Errorf("existing comment lost:\n%s", body)
	}
	if !strings.Contains(body, "package-ecosystem: docker") {
		t.Errorf("docker entry not appended:\n%s", body)
	}
	if _, err := Parse(d.Data); err != nil {
		t.Fatalf("extended config does not parse: %v\n%s", err, body)
	}
}

func TestDiscoverUpToDate(t *testing.T) {
	existing := []byte(`version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
`)
	d, err := Discover(existing, []Detected{{Ecosystem: "gomod", Directories: []string{"/"}}})
	if err != nil {
		t.Fatalf("Discover: %v", err)
	}
	if d.Changed {
		t.Errorf("nothing should change: %+v", d)
	}
	if len(d.Notes) == 0 {
		t.Error("expected up-to-date note")
	}
}

func TestDiscoverExtendInvalidConfig(t *testing.T) {
	if _, err := Discover([]byte("version: 1\nupdates: []\n"), []Detected{{Ecosystem: "gomod"}}); err == nil {
		t.Fatal("expected parse error for invalid existing config")
	}
}

func TestAppendUpdatesNoUpdatesKey(t *testing.T) {
	// A document missing the updates key gets one created.
	out, err := appendUpdates([]byte("version: 2\n"), []Update{bestPracticeUpdate("gomod", []string{"/"})})
	if err != nil {
		t.Fatalf("appendUpdates: %v", err)
	}
	if !strings.Contains(string(out), "package-ecosystem: gomod") {
		t.Errorf("entry not added:\n%s", out)
	}
}

func TestCommitPrefix(t *testing.T) {
	if commitPrefix("github-actions") != "ci" {
		t.Error("github-actions should use ci")
	}
	if commitPrefix("gomod") != "chore" {
		t.Error("default should be chore")
	}
}

func TestRenderDiscovery(t *testing.T) {
	tests := []struct {
		name   string
		disc   Discovery
		dryRun bool
		want   []string
	}{
		{"created", Discovery{Owner: "o", Repo: "r", Path: "p", Created: true, Changed: true, Added: []string{"gomod"}, Data: []byte("version: 2\n")}, false, []string{"Created p", "gomod", "version: 2"}},
		{"would create", Discovery{Owner: "o", Repo: "r", Path: "p", Created: true, Changed: true, Added: []string{"gomod"}, Data: []byte("x")}, true, []string{"Would create"}},
		{"added", Discovery{Owner: "o", Repo: "r", Path: "p", Changed: true, Added: []string{"docker"}, Data: []byte("y")}, false, []string{"Added 1 ecosystem(s)", "docker"}},
		{"uptodate", Discovery{Owner: "o", Repo: "r", Path: "p", Notes: []string{"all covered"}}, false, []string{"already covers", "all covered"}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var b bytes.Buffer
			RenderDiscovery(&b, &tt.disc, tt.dryRun)
			for _, w := range tt.want {
				if !strings.Contains(b.String(), w) {
					t.Errorf("missing %q in:\n%s", w, b.String())
				}
			}
		})
	}
}

func TestEncodeDiscoveryJSON(t *testing.T) {
	d := Discovery{Owner: "o", Repo: "r", Path: "p", Changed: true, Added: []string{"npm"}, Data: []byte("version: 2\n")}
	var b bytes.Buffer
	if err := EncodeDiscoveryJSON(&b, &d); err != nil {
		t.Fatalf("encode: %v", err)
	}
	var doc DiscoveryDocument
	if err := json.Unmarshal(b.Bytes(), &doc); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if !doc.Updated || doc.UpToDate || doc.Created {
		t.Errorf("flags wrong: %+v", doc)
	}
	if len(doc.Added) != 1 || doc.Added[0] != "npm" {
		t.Errorf("added = %v", doc.Added)
	}
	if doc.Config != "version: 2\n" {
		t.Errorf("config = %q", doc.Config)
	}
}

func TestNewDiscoveryDocumentNonNil(t *testing.T) {
	doc := NewDiscoveryDocument(&Discovery{Owner: "o", Repo: "r"})
	if doc.Added == nil || doc.Notes == nil {
		t.Error("slices must be non-nil")
	}
	if !doc.UpToDate {
		t.Error("unchanged discovery should be up to date")
	}
}
