# This file was generated by GoReleaser. DO NOT EDIT.
cask "shuck" do
  version "0.3.4"

  on_macos do
    on_intel do
      sha256 "fa9efcd7c72b8dca53fd242f13cfbace83e90cb120b72bfa193997097883bc27"
      url "https://github.com/justanotherspy/shuck/releases/download/v#{version}/shuck_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/justanotherspy/shuck/"
    end
    on_arm do
      sha256 "2b98992afa1acd8c7e35c4fd8d69792a153ce6a0f8bebd4f2526388993b7e89a"
      url "https://github.com/justanotherspy/shuck/releases/download/v#{version}/shuck_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/justanotherspy/shuck/"
    end
  end

  on_linux do
    on_intel do
      sha256 "452704768344f834a5621ee145d8a389cebf6e7fa923cf903d8a1d7ddeb1de69"
      url "https://github.com/justanotherspy/shuck/releases/download/v#{version}/shuck_#{version}_linux_amd64.tar.gz",
        verified: "github.com/justanotherspy/shuck/"
    end
    on_arm do
      sha256 "95cf468b7c77180300d0dd7ab1916ee3646e471a2f32a401a9d4e7598ead6bf5"
      url "https://github.com/justanotherspy/shuck/releases/download/v#{version}/shuck_#{version}_linux_arm64.tar.gz",
        verified: "github.com/justanotherspy/shuck/"
    end
  end

  name "shuck"
  desc "Print the exact failing CI step logs for a GitHub PR"
  homepage "https://github.com/justanotherspy/shuck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shuck"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shuck"]
    end
  end

  # No zap stanza required

end
