apiVersion: v1
kind: Service
metadata:
  name: {{ include "shuck.fullname" . }}-gateway
  labels:
    {{- include "shuck.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: http
    {{- include "shuck.metricsServicePort" . | nindent 4 }}
  selector:
    {{- include "shuck.selectorLabels" (dict "root" . "component" "gateway") | nindent 4 }}
