{{- if .Values.portal.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shuck.fullname" . }}-portal
  labels:
    {{- include "shuck.labels" . | nindent 4 }}
    app.kubernetes.io/component: portal
spec:
  type: {{ .Values.portal.service.type }}
  ports:
    - name: http
      port: {{ .Values.portal.service.port }}
      targetPort: http
  selector:
    {{- include "shuck.selectorLabels" (dict "root" . "component" "portal") | nindent 4 }}
{{- end }}
